import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

import { Header, PageContent, PageTitle } from '@/components'

const allScripts = [
  'yarn add aboutme',
  '############# Installing dependencies #############',
  'Full stack developer junior',
  'Clean code enthusiast and technology lover',
  'Javascript and typescript maniac',
  'Play some games and read some manga :)',
]

const scriptVelocityInMs = 50

export default function Home() {
  const [scripts, setScripts] = useState(allScripts.map((_) => ''))
  const [currentScript, setCurrentScript] = useState(0)

  function resolverScript(scriptIndex: number) {
    setTimeout(() => {
      setScripts((state) => {
        const newScripts = state.map((script, idx, self) => {
          if (idx === scriptIndex) {
            const string = allScripts[idx]
            const newCharacter = string[self[idx].length]
            return newCharacter ? script + newCharacter : script
          }
          return script
        })
        return newScripts
      })
    }, scriptVelocityInMs)
  }

  useEffect(() => {
    if (scripts[currentScript] !== allScripts[currentScript]) {
      resolverScript(currentScript)
    } else if (currentScript <= allScripts.length) {
      setCurrentScript((old) => old + 1)
    }
  }, [scripts, currentScript])

  return (
    <div className="max-w-screen min-h-screen overflow-hidden">
      <Head>
        <title>Vineboneto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="h-screen flex justify-center items-center" style={{ backgroundImage: 'url(/topography.svg)' }}>
        <div className="mockup-code w-[650px]">
          {scripts.map((script, idx) => {
            if (script || idx === 0) {
              let className = ''
              let prefix = '~'

              if (idx === 0) prefix = '$'
              if (idx === 1) {
                prefix = '>'
                className = 'text-success'
              }
              if (idx === 5) className = 'text-yellow-500'

              return (
                <pre data-prefix={prefix} key={idx} className={className}>
                  {script}
                </pre>
              )
            }
          })}
        </div>
      </div>

      <div className="h-screen">
        <PageContent>
          <div className="w-[650px] space-y-6">
            <PageTitle>About</PageTitle>
            <div className="flex">
              <div className="avatar mr-10">
                <div className="w-24 rounded-full">
                  <Image src="https://github.com/vineboneto.png" alt="avatar" width="100%" height="100%" />
                </div>
              </div>
              <ul className="list-disc">
                <li>Nome: Vinicius Gazolla Boneto</li>
                <li>Função: Escreve alguns códigos por ae</li>
                <li>Onde: Videira - Brazil</li>
                <li>Contato: vineboneto@gmail.com</li>
              </ul>
            </div>
            <p className="text-justify leading-7">
              Atualmente sou desenvolvedor full stack júnior, onde desenvolvo sistemas internos e websites completos
              para empresas da região. No meu desenvolvimento profissional a principal tecnologia que utilizei e utilizo
              é javascript/typescript, tanto na criação de interfaces gráficas que seguem conceitos de UX/UI, quanto no
              desenvolvimento de webservices que seguem arquitetura REST. Sempre estou buscando novos horizontes de
              conhecimento sobre outras/novas tecnologias que despertam o meu interesse.
            </p>

            <div className="grid grid-cols-3 gap-4">
              <div className="card glass">
                <div className="card-body">
                  <h2 className="card-title">Backend</h2>
                  <ul className="list-disc">
                    <li>NodeJS</li>
                    <li>Typescript</li>
                    <li>Clean Architecture</li>
                    <li>Express</li>
                    <li>Elixir (learning)</li>
                    <li>SQL</li>
                  </ul>
                </div>
              </div>
              <div className="card glass">
                <div className="card-body">
                  <h2 className="card-title">Frontend</h2>
                  <ul className="list-disc">
                    <li>ReactJS</li>
                    <li>CSS; Tailwind...</li>
                    <li>HTML</li>
                  </ul>
                </div>
              </div>
              <div className="card glass">
                <div className="card-body">
                  <h2 className="card-title">Mobile</h2>
                  <ul className="list-disc">
                    <li>React Native</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </PageContent>
      </div>
      <div className="h-screen" style={{ backgroundImage: 'url(/topography.svg)' }}>
        <PageContent>
          <div className="w-[650px] space-y-6">
            <PageTitle>Experiência</PageTitle>
            <div className="space-y-4">
              <div className="card shadow-xl card-bordered bg-base-300">
                <div className="card-body">
                  <h2 className="card-title">SECRETÁRIA MUNICIPAL E SAÚDE</h2>
                  <span>Ago 2019 - Ago 2021 | Videira, SC</span>
                  <p>Suporte ao usuário, manutenção de computadores e impressoras</p>
                </div>
              </div>
              <span>Adicionar flecha</span>
              <div className="card shadow-xl card-bordered bg-base-300">
                <div className="card-body">
                  <h2 className="card-title">SKORETECH SOLUÇÕES EM TECNOLOGIA LTDA</h2>
                  <span>Ago 2021 - Presente | Videira, SC</span>
                  <p>Desenvolvimento de sistemas completos para gestão de empresas.</p>
                </div>
              </div>
            </div>
          </div>
        </PageContent>
      </div>

      <div className="h-screen bg-gradient-to-r from-base-100 to-base-300">
        <PageContent>
          <div className="w-[650px] space-y-6">
            <PageTitle>Portfólio</PageTitle>
            <div className="space-y-4">
              <div className="card shadow-xl card-bordered bg-base-300">
                <div className="card-body">
                  <a className="card-title link link-hover">Turing Machine</a>
                  <p>Máquina de turing (Trabalho de faculdade). Eu realmente não lembro como isso funciona</p>
                </div>
              </div>
              <span>Adicionar flecha</span>
              <div className="card shadow-xl card-bordered bg-base-300">
                <div className="card-body">
                  <a className="card-title link link-hover">N queens hill climbing</a>
                  <p>Resolução do problema das 8 rainhas em um tabuleiro utilizando algoritmo de busca hill climbing</p>
                </div>
              </div>
              <div className="card shadow-xl card-bordered bg-base-300">
                <div className="card-body">
                  <a className="card-title link link-hover">DWL Web</a>
                  <p>Converte videos do youtube para mp3/mp4</p>
                </div>
              </div>
            </div>
          </div>
        </PageContent>
      </div>

      <footer className="footer footer-center p-10 bg-base-200 text-base-content rounded">
        <div className="grid grid-flow-col gap-4">
          <a className="link link-hover">About</a>
          <a className="link link-hover">Contact</a>
          <a className="link link-hover">Jobs</a>
          <a className="link link-hover">Press kit</a>
        </div>
        <div>
          <div className="grid grid-flow-col gap-4">
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current"
              >
                <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current"
              >
                <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current"
              >
                <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
              </svg>
            </a>
          </div>
        </div>
        <div>
          <p>Copyright © 2022 - All right reserved for me :)</p>
        </div>
      </footer>
    </div>
  )
}
