import Head from 'next/head'
import { Header } from '@/components'

export default function Home() {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Vineboneto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  )
}
